=== allen-garvey/personal-website/code/xml_bookstore/models/allBooks.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="record" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ISBN" type="xs:string"/>
							<xs:element name="Title" type="xs:string"/>
							<xs:element name="Category" type="categoryType"/>
							<xs:element name="Description" type="xs:string"/>
							<xs:element name="Price" type="currencyType"/>
							<xs:element name="au_firstname" type="xs:string"/>
							<xs:element name="au_lastname" type="xs:string"/>
							<xs:element name="Coverpic" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="categoryType">
    	<xs:restriction base="xs:string">
        	<xs:enumeration value="Database" />
        	<xs:enumeration value="Web" />
        	<xs:enumeration value="Graphics" />
        	<xs:enumeration value="Programming" />
        	<xs:enumeration value="JavaScript" />
        	<xs:enumeration value="HTML" />
    	</xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="currencyType">
    	<xs:restriction base="xs:decimal">
        	<xs:minInclusive value="0" />
        	<xs:fractionDigits value="2" />
    	</xs:restriction>
    </xs:simpleType>

</xs:schema>

=== allen-garvey/personal-website/interactive/xml_bookstore/models/allBooks.xml
<?xml version="1.0"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="allBooks.xsd">
	<record>
		<ISBN>0-07-882122-3</ISBN>
		<Title>Oracle: A Beginner&apos;s Guide</Title>
		<Category>Database</Category>
		<Description>A beginner&apos;s guide to the complex and powerful Oracle database management system. Teaches you how to set up, query and manage your database, including principles of database design, how to manage data, generate reports and tune the system for optimal performance.</Description>
		<Price>30.00</Price>
		<au_firstname>Michael</au_firstname>
		<au_lastname>Abbey</au_lastname>
		<Coverpic>images/Oracle.JPG</Coverpic>
	</record>
	<record>
		<ISBN>0-201-43787-7</ISBN>
		<Title>Creating Killer Interactive Web Sites : The Art of Integrating Interactivity and Design</Title>
		<Category>Web</Category>
		<Description>Creating Killer Interactive Sites is the one-of-a-kind look into the secrets of one of the world&apos;s most preeminent Web design firms. Its highly visual, inspiring approach brings a new standard to integrating design and interactivity to create successful sites. The book&apos;s companion Web site includes all the code and examples from the book, valuable tools and utilities, plus updated new, information, and tips.</Description>
		<Price>39.99</Price>
		<au_firstname>Deke</au_firstname>
		<au_lastname>McClelland</au_lastname>
		<Coverpic>images/KillerInteractiveSites.gif</Coverpic>
	</record>
	<record>
		<ISBN>0-201-44787-8</ISBN>
		<Title>The Practical SQL Handbook</Title>
		<Category>Database</Category>
		<Description>The best-selling guide to learning SQL, the standard language for accessing information in relational databases. Teaches SQL as it&apos;s really used, with step-by-step lessons in the basic vocabulary and functions of the language and the processes and issues involved in developing robust applications.</Description>
		<Price>40.12</Price>
		<au_firstname>Judith</au_firstname>
		<au_lastname>Bowman</au_lastname>
		<Coverpic>images/PracticalSQL.JPG</Coverpic>
	</record>
	<record>
		<ISBN>0-672-30956-4</ISBN>
		<Title>SQL Server 6.5 Second Edition</Title>
		<Category>Database</Category>
		<Description>Comprehensive guide to Microsoft SQL Server 6.5, including the latest enhancements such as Distributed Transaction Coordinator (DTC), replication to ODBC clients, SQL Enterprise Manager and SQL Web Assistant, SQL language enhancements.</Description>
		<Price>60.00</Price>
		<au_firstname>David</au_firstname>
		<au_lastname>Solomon</au_lastname>
		<Coverpic>images/SQLUnleashed.jpg</Coverpic>
	</record>
	<record>
		<ISBN>0-7645-4032-7</ISBN>
		<Title>Photoshop 4 for Windows 95 Bible</Title>
		<Category>Graphics</Category>
		<Description>Comprehensive reference for Photoshop users includes step-by-step guides to everything from working wonders with layers to customizing graphics for the World Wide Web.</Description>
		<Price>50.23</Price>
		<au_firstname>Deke</au_firstname>
		<au_lastname>McClelland</au_lastname>
		<Coverpic>images/PS4Bible.JPG</Coverpic>
	</record>
	<record>
		<ISBN>1-26592-234-2</ISBN>
		<Title>Web Page Design : A Different Multimedia</Title>
		<Category>Web</Category>
		<Description>Revealing the crucial differences between an ordinary Web page and an effective site, bestselling Internet author Mary E. S. Morris and co-author Randy J. Hinrichs go beyond the basics of web creation to show readers how to tackle the crucial problems of information overload at your Web site, getting lost in cyberspace, bandwidth constraints required to hold a user&apos;s attention, and more.</Description>
		<Price>19.96</Price>
		<au_firstname>David</au_firstname>
		<au_lastname>Flanagan</au_lastname>
		<Coverpic>images/WebPageDesign.gif</Coverpic>
	</record>
	<record>
		<ISBN>1-549514-32-1</ISBN>
		<Title>Information Architecture for the World Wide Web</Title>
		<Category>Web</Category>
		<Description>With a swift and convincing stroke, the authors of Information Architecture for the World Wide Web tear down many entrenched ideas about Web design. Flashy animations are cool, they agree, as long as they don&apos;t irritate the viewer. Nifty clickable icons are nice, but are their meanings universal? Is the search engine providing results that are useful and relevant? This book acts as a mirror and with careful questioning causes the reader to think through all the elements and decisions required for well-crafted Web design.</Description>
		<Price>19.34</Price>
		<au_firstname>Louis</au_firstname>
		<au_lastname>Rosenfeld</au_lastname>
		<Coverpic>images/InformationArchitecture.gif</Coverpic>
	</record>
	<record>
		<ISBN>1-56204-223-1</ISBN>
		<Title>The Non-Designer&apos;s Web Book : An Easy Guide to Creating, Designing, and Posting Your Own Web Site</Title>
		<Category>Web</Category>
		<Description>The Non-Designer&apos;s Web Book is a pretty, full-color guide for aspiring Web designers. The authors first explain how to browse and search the Web and then discuss how to plan and post a Web site. Then they get you into the real work of designing Web sites, whether for business or personal purposes. The authors teach you basic design principles--covering such areas as alignment, proximity, repetition, and contrast--and then discuss design issues that are specific to the Web: You learn about creating pages with careful attention to color, graphics, typography, tables, and more. Finally, you learn how to test, fix, upload, update, and register your site. The book isn&apos;t an HTML primer, but you do get a few tips on tweaking your pages by editing HTML code.</Description>
		<Price>23.96</Price>
		<au_firstname>Robin</au_firstname>
		<au_lastname>Williams</au_lastname>
		<Coverpic>images/NonDesignerWebBook.gif</Coverpic>
	</record>
	<record>
		<ISBN>1-56542-264-4</ISBN>
		<Title>Elements of Web Design : The Designer&apos;s Guide to a New Medium</Title>
		<Category>Graphics</Category>
		<Description>Elements of Web Design helps designers learn how the experts plan and design their Web sites. It&quot;s ideal for readers who haven&quot;t yet learned what the Web is all about, but who&apos;d like to start applying their design and management skills to Web-site production. The book provides a history of the Web, examples of well-designed sites, and information on coding HTML and preparing Web graphics.</Description>
		<Price>31.96</Price>
		<au_firstname>Michael</au_firstname>
		<au_lastname>Groh</au_lastname>
		<Coverpic>images/ElementsOfWebDesign.gif</Coverpic>
	</record>
	<record>
		<ISBN>1-56592-234-4</ISBN>
		<Title>JavaScript: The Definitive Guide</Title>
		<Category>Programming</Category>
		<Description>A thorough description of the JavaScript programming language, complete with sophisticated programming examples, as well as a definitive, in-depth reference section covering each JavaScript function, object method, property and event handler.</Description>
		<Price>33.23</Price>
		<au_firstname>David</au_firstname>
		<au_lastname>Flanagan</au_lastname>
		<Coverpic>images/JavaScript.JPG</Coverpic>
	</record>
	<record>
		<ISBN>1-56604-286-0</ISBN>
		<Title>The Visual Guide to Microsoft Access for Windows 95</Title>
		<Category>Database</Category>
		<Description>A graphical approach to using Microsoft Access 95 to build, customize and manage databases.</Description>
		<Price>35.36</Price>
		<au_firstname>Michael</au_firstname>
		<au_lastname>Groh</au_lastname>
		<Coverpic>images/MSAccess.JPG</Coverpic>
	</record>
	<record>
		<ISBN>1-56884-230-9</ISBN>
		<Title>Visual Basic 4 for Windows for Dummies</Title>
		<Category>Programming</Category>
		<Description>The fun and easy way to learn the fundamentals of Windows programming with Visual Basic. For novice programmers and seasoned professionals who want an easy-to-use reference, this book shows you how to use Visual Basic to begin programming and designing attractive interfaces in no time, without any intimidating jargon.</Description>
		<Price>20.99</Price>
		<au_firstname>Deke</au_firstname>
		<au_lastname>McClelland</au_lastname>
		<Coverpic>images/VBDummies.JPG</Coverpic>
	</record>
	<record>
		<ISBN>1-57521-014-2</ISBN>
		<Title>Teach Yourself Web Publishing With HTML in 14 Days</Title>
		<Category>HTML</Category>
		<Description>Step-by-step guide to learning HTML and Web publishing--everything from the fundamentals of creating a simple home page to the intricacies of designing and creating elaborate Web sites with advanced HTML and CGI scripts.</Description>
		<Price>40.34</Price>
		<au_firstname>Laura</au_firstname>
		<au_lastname>Lemay</au_lastname>
		<Coverpic>images/WebPubHTML.jpg</Coverpic>
	</record>
	<record>
		<ISBN>1-845577-86-7</ISBN>
		<Title>Designing With JavaScript : Creating Dynamic Web Pages</Title>
		<Category>JavaScript</Category>
		<Description>Designing with JavaScript is an excellent learn-by-example tutorial that helps you create dynamic content for your Web site. Each chapter tackles a single topic with a relaxed and conversational tone. The thoroughly explained examples in each chapter are blocked off in green for quick reference and included on the accompanying CD-ROM.</Description>
		<Price>23.96</Price>
		<au_firstname>Nick</au_firstname>
		<au_lastname>Heinle</au_lastname>
		<Coverpic>images/DesigningWithJavaScript.gif</Coverpic>
	</record>
	<record>
		<ISBN>1-861001-26-6</ISBN>
		<Title>Active Server Pages 2.0 Professional Guide</Title>
		<Category>Web</Category>
		<Description>Professional Guide  to Microsoft&apos;s server-based technology desinged to create dynamically generated HTML pages for the World Wide Web or corporate internets.Explains how Active Server pages fit into the grand scheme of things and how you can use it to build great web sites and intranet applications</Description>
		<Price>60.00</Price>
		<au_firstname>Alex</au_firstname>
		<au_lastname>Federov</au_lastname>
		<Coverpic>images/ProASP.jpg</Coverpic>
	</record>
	<record>
