=== allen-garvey/personal-website/code/pstart2/models/bookmarks.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="bookmarks">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="bookmark-list" type="bookmarkListType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="bookmarkListType">
		<xs:sequence>
			<xs:element name="title" type="nonEmptyString" minOccurs="1" maxOccurs="1" />
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="divider" type="dividerType" />
				<xs:element name="a" type="aType" />
			</xs:choice>
		</xs:sequence>
		<xs:attributeGroup ref="bookListAttributes" />
		<xs:attributeGroup ref="sharedCommonAttributes" />
	</xs:complexType>

	<xs:complexType name="dividerType">
		<xs:attributeGroup ref="sharedCommonAttributes" />
		<xs:attributeGroup ref="sharedChildAttributes" />
	</xs:complexType>

	<xs:complexType name="aType">
		<xs:simpleContent>
			<xs:extension base="nonEmptyString">
				<xs:attributeGroup ref="aAttributes" />
				<xs:attributeGroup ref="sharedCommonAttributes" />
				<xs:attributeGroup ref="sharedChildAttributes" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:attributeGroup name="sharedCommonAttributes">
		<xs:attribute name="comment" type="xs:string" use="optional" />
		<xs:attribute name="secure" type="xs:boolean" default="false" use="optional" />
		<xs:attribute name="max-device-code" type="deviceRequiredCode" use="optional" default="100" />
		<xs:attribute name="display" type="xs:boolean" default="true" use="optional" />
	</xs:attributeGroup>

	<xs:attributeGroup name="sharedChildAttributes">
		<!-- min-device-code inherits from parent bookmark-list if not set -->
		<xs:attribute name="min-device-code" type="deviceRequiredCode" use="optional" />
	</xs:attributeGroup>

	<xs:attributeGroup name="bookListAttributes">
		<xs:attribute name="id" type="xs:ID" use="required" />
		<xs:attribute name="title-color" type="colorType" use="optional" default="black" />
		<xs:attribute name="min-device-code" type="deviceRequiredCode" use="required" />
	</xs:attributeGroup>

	<xs:attributeGroup name="aAttributes">
		<xs:attribute name="href" type="xs:string" use="required" />
	</xs:attributeGroup>

	<xs:simpleType name="nonEmptyString">
    	<xs:restriction base="xs:string">
			<xs:pattern value="(\s*[^\s]\s*)+"></xs:pattern>
    	</xs:restriction>
    </xs:simpleType>

    <!-- used to determine the css class used to display the color of the title -->
    <xs:simpleType name="colorType">
    	<xs:restriction base="xs:string">
        	<xs:enumeration value="black" />
        	<xs:enumeration value="white" />
        	<xs:enumeration value="pink" />
        	<xs:enumeration value="red" />
        	<xs:enumeration value="orange" />
        	<xs:enumeration value="yellow" />
        	<xs:enumeration value="green" />
        	<xs:enumeration value="blue" />
        	<xs:enumeration value="dodgerBlue" />
        	<xs:enumeration value="purple" />
    	</xs:restriction>
    </xs:simpleType>

<!-- see min-max-device-code-readme.txt for explanation -->
    <xs:simpleType name="deviceRequiredCode">
    	<xs:restriction base="xs:nonNegativeInteger">
        	<xs:minInclusive value="0" />
        	<xs:maxInclusive value="100" />
    	</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== allen-garvey/personal-website/interactive/pstart2/models/bookmarks1.xml
<!-- last edited 11/29/2014 -->
<bookmarks xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xsi:noNamespaceSchemaLocation='bookmarks.xsd' >

   <!-- for now (11/28/2014) using min-device-code = '90' (laptop) for desktop and 
		min-device-code = '50' (ipod/iphone and larger) for mobile -->
		<!-- see min-max-device-code-readme.txt for further explanation of device-codes used -->

	<bookmark-list id='m_contents_list' min-device-code='90' title-color='green' secure='true'>
		<title>M</title>
		<a href='https://onlinebanking.tdbank.com'>TD Bank</a>
		<a href='http://www.bankofamerica.com'>Bank of America</a>
		<a href='http://www.chase.com/amazon'>Chase</a>
		<divider />
		<a href='http://1fbusa.com'>1FBUSA</a>
		<a href='https://personal.vanguard.com/us/home?fromPage=portal'>Vanguard</a>
	</bookmark-list>

	<bookmark-list id='t_contents_list' min-device-code='90' title-color='blue' secure='true'>
		<title>T</title>
		<a href='https://duckduckgo.com/?q=what+is+my+ip'>Duck Duck Go</a>
		<a href='http://www.kat.ph'>Kat</a>
		<a href='http://www.thepiratebay.se' display='false'>The Pirate Bay</a>
		<a href='http://www.bitsnoop.com/'>Bitsnoop</a>
	</bookmark-list>

	<bookmark-list id='tr_contents_list' min-device-code='50' title-color='blue'>
		<title>T</title>
		<a href='https://duckduckgo.com/?q=what+is+my+ip' min-device-code='90' secure='true'>Duck Duck Go</a>
		<a href='http://www.kat.ph' min-device-code='90' secure='true'>Kat</a>
		<a href='http://www.thepiratebay.se' min-device-code='90' secure='true' display="false">The Pirate Bay</a>
		<a href='http://www.bitsnoop.com/' min-device-code='90' secure='true'>Bitsnoop</a>
		<divider min-device-code='90' secure='true' />
		<a href='http://www.greenwichlibrary.org' min-device-code='70'>Greenwich</a>
		<a href='http://www.fergusonlibrary.org' min-device-code='70'>Ferguson</a>
		<a href='http://newcanaanlibrary.org' min-device-code='70'>New Canaan</a>
		<a href='http://www.purchase.edu/departments/library/' min-device-code='70'>Purchase</a>
		<divider min-device-code='70' />
		<a href='http://www.amazon.com'>Amazon</a>
	</bookmark-list>

	<bookmark-list id='l_contents_list' min-device-code='50' title-color='yellow'>
		<title>L</title>
		<a href='http://localhost' min-device-code='90' secure='true'>Localhost</a>
		<a href='http://localhost:8080' min-device-code='90' secure='true' display='false'>Tomcat</a>
		<a href='http://localhost/internet_list' min-device-code='90' secure='true' display='false'>Internet List</a>
		<a href='http://localhost/movie_list_2' min-device-code='90' secure='true'>Movie List</a>
		<divider min-device-code='90' secure='true' />
		<a href='http://www.allengarvey.com'>Allen Garvey</a>
		<a href='http://www.bitterpolarbear.com'>Bitter Polar Bear</a>
		<a href='http://www.strangescenery.com'>Strange Scenery</a>
		<divider min-device-code='90' secure='true' />
		<a href='http://www.dreamhost.com' min-device-code='90' secure='true'>Dreamhost</a>
	</bookmark-list>

	<bookmark-list id='x_contents_list' min-device-code='50' title-color='pink'>
		<title>X</title>
		<a href='http://www.baseballprospectus.com'>Baseball Prospectus</a>
		<a href='http://www.mlbtraderumors.com'>MLB Trade Rumors</a>
		<a href='http://www.macrumors.com'>Mac Rumors</a>
		<divider min-device-code='70' />
		<a href='http://www.gmail.com' min-device-code='90'>Gmail</a>
		<a href='http://www.facebook.com' min-device-code='90' display='false'>Facebook</a>
		<a href='https://www.hotmail.com/' min-device-code='90'>Hotmail</a>
		<a href='http://trailers.apple.com' min-device-code='70' display='false'>Apple Trailers</a>
		<a href='http://www.xkcd.com' display='false'>XKCD</a>
		<a href='http://www.returnofkings.com' display='false'>Return of Kings</a>
		<a href='http://www.tynan.com' min-device-code='70' display='false'>Tynan</a>
		<a href='http://www.nytimes.com/pages/magazine' min-device-code='70' display='false'>NY Times Magazine</a>
	</bookmark-list>

	<bookmark-list id='y_contents_list' min-device-code='50' title-color='purple'>
		<title>Y</title>
		<a href='http://www.xkcd.com'>XKCD</a>
		<a href='http://www.ign.com'>IGN</a>
		<divider />
		<a href='http://www.facebook.com' min-device-code='90'>Facebook</a>
		<a href='http://trailers.apple.com' min-device-code='70'>Apple Trailers</a>
		<divider min-device-code='70' />
		<a href='http://www.returnofkings.com'>Return of Kings</a>
		<a href='http://www.nytimes.com/pages/magazine' min-device-code='70'>NY Times Magazine</a>
	</bookmark-list>

	<bookmark-list id='r_contents_list' min-device-code='90' title-color='red'>
		<title>R</title>
		<a href='http://www.greenwichlibrary.org'>Greenwich</a>
		<a href='http://www.fergusonlibrary.org'>Ferguson</a>
		<a href='http://newcanaanlibrary.org'>New Canaan</a>
		<a href='http://www.nypl.org'>NYPL</a>
		<a href='http://www.suny.edu/puchase'>Purchase</a>
		<a href='http://libweb.hofstra.edu/search/t'>Lexicat</a>
	</bookmark-list>

	<bookmark-list id='c_contents_list' min-device-code='50' title-color='dodgerBlue'>
		<title>C</title>
		<a href='http://news.ycombinator.com'>Hacker News</a>
		<a href='http://www.thedailywtf.com'>The Daily WTF</a>
		<divider />
		<a href='http://www.thecodist.com'>The Codist</a>
		<a href='http://www.codinghorror.com'>Coding Horror</a>
		<a href='http://www.dereksivers.com'>Derek Sivers</a>
		<a href='http://thecodelesscode.com/contents'>Codeless Code</a>
		<divider min-device-code='70' />
		<a href='http://newyork.craigslist.org' min-device-code='70'>Craigslist</a>
	</bookmark-list>

	<bookmark-list id='e_contents_list' min-device-code='50' title-color='orange'>
		<title>E</title>
		<a href='http://my.commnet.edu' display='false'>my.commnet</a>
		<a href='https://learn-cc.ct.edu/webapps/login/'>Blackboard</a>
		<a href='http://www.ncc.commnet.edu/default.asp'>NCC</a>
		<a href='http://read.amazon.com' min-device-code='90' display='false'>Amazon Cloud Reader</a>
		<a href='https://www.pinterest.com' min-device-code='90' display='false'>Pinterest</a>
		<a href='https://norwalk.digication.com/' min-device-code='90'>Digication</a>
		<divider min-device-code='90' />
		<a href='https://www.propellerheads.se/blog/tutorials/ask-dr-rex/' min-device-code='90'>Reason Tutorials</a>
		<divider min-device-code='90' />
		<a href='http://play.typeracer.com' min-device-code='90'>Type Racer</a>
		<a href='http://www.keybr.com' min-device-code='90'>Typing Trainer</a>
		<a href='http://www.powertyping.com' min-device-code='90'>Dvorak Trainer</a>
	</bookmark-list>

	<bookmark-list id='b_contents_list' min-device-code='85' title-color='red'>
		<title>B</title>
		<a href='https://www.coursera.org' display='false'>Coursera</a>
		<a href='https://www.edx.org' display='false'>edX</a>
		<a href='http://www.learnhowtoprogram.com/table-of-contents'>Epicodus</a>
		<a href='https://www.codeschool.com' display='false'>Code School</a>
		<a href='http://www.khanacademy.org'>Khan Academy</a>
		<a href='http://teamtreehouse.com'>Team Treehouse</a>
		<divider />
		<a href='http://c.learncodethehardway.org/book/'>C The Hard Way</a>
		<a href='http://cli.learncodethehardway.org/book/'>CLI The Hard Way</a>
		<divider />
		<a href='http://www.codecademy.com' display='false'>Codecademy</a>
		<a href='http://www.freecodecamp.com' display='false'>Free Code Camp</a>
		<a href='http://www.theodinproject.com' display='false'>The Odin Project</a>
		<divider display='false' />
		<a href='http://www.nodebeginner.org/#javascript-and-nodejs' display='false'>Node Beginner Tutorial</a>
		<a href='http://nodeschool.io' display='false'>Nodeschool</a>
		<divider display='false' />
		<a href='http://www.thinkful.com' display='false'>Thinkful</a>
		<a href='https://developers.google.com/edu/python/introduction?csw=1'>Google Python Tutorial</a>
		<a href='http://cs50.tv/2013/fall/' display='false'>Harvard Intro to Compsci</a>
		<a href='http://see.stanford.edu/see/courses.aspx' display='false'>Stanford Intro to Compsci</a>
		<a href='http://www.ccs.neu.edu/home/matthias/HtDP2e/'>How to Design Programs</a>
		<divider />
		<a href='https://hackdesign.org'>Hack Design</a>
		<a href='http://gameprogrammingpatterns.com/contents.html' display='false'>Game Programming Patterns</a>
	</bookmark-list>

	<bookmark-list id='z_contents_list' min-device-code='85' title-color='black'>
		<title>Z</title>
		<a href='http://www.propellerheads.se'>Propellerhead</a>
		<a href='http://www.reason101.net'>Reason 101</a>
		<a href='http://www.tcelectronic.com'>TC Electronic</a>
		<a href='http://decidedlydusty.tumblr.com'>Musicomics</a>
		<a href='http://www.ign.com/ps4' display='false' >IGN PS4</a>
		<a href='https://www.monocreators.com'>Mono</a>
		<a href='http://www.redoxx.com'>Red Oxx</a>
	</bookmark-list>

</bookmarks>
